config/routes.rb
Channels::Application.routes.draw do

  #static pages
  match "about" => "pages#about"
  #match "jobs" => "pages#jobs"
  #match "our-team" => "pages#our_team", :as => "our_team"
  #match "press" => "pages#press"
  #match "faq" => "pages#faq"
  #match "customer-support" => "pages#customer_support", :as => "customer_support"
  match "safe-harbor" => "pages#safe_harbor", :as => "safe_harbor"
  match "altimarc-for-your-business" => "pages#altimarc_for_your_business", :as => "altimarc_for_your_business"
  match "privacy" => "pages#privacy", :as => "privacy"
  match "refund" => "pages#refund", :as => "refund"
  match "terms" => "pages#terms", :as => "terms"
  match "copyrights" => "pages#copyrights", :as => "copyrights"
  match "randy-owen-altimarc-coming-soon-video" => "home#index"

  resources :press, :only => [:index, :show]

  #old giveaways
  match "giveaways/kentucky-derby-with-randy-owen" => "giveaways#derby", :as => "derby"
  match "kentucky-derby-with-randy-owen" => redirect("/giveaways/kentucky-derby-with-randy-owen")
  match "giveaways/cma-fanfest" => "giveaways#cma", :as => "cma"
  match "cma-fanfest-with-randy-owen" => redirect("/giveaways/cma-fanfest")
  match "giveaways/thank-you" => "giveaways#thankyou", :as => "thankyou"
  match "t-shirt" => redirect("/giveaways/t-shirt")
  match "giveaways/t-shirt" => "giveaways#tshirt", :as => "tshirt"
  match "giveaways/1965-chevrolet-chevelle" => "giveaways#car", :as => "car"

  #giveaways email
  #match "enter-giveaways(/:id)" => "giveaways#enter_giveaway", :as => 'enter_giveaway'
  match "enter-giveaways" => "giveaways#enter_giveaway", :as => 'enter_giveaway'

  #zencoder
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  post "teaser-zencoder-callback" => "zencoder_callback#teaser", :as => "teaser_zencoder_callback"
  post "performance-zencoder-callback" => "zencoder_callback#performance", :as => "performance_zencoder_callback"
  post "preview-zencoder-callback" => "zencoder_callback#preview", :as => "preview_zencoder_callback"

  #channels
  resources :giveaways, :only => [:index]
  resources :posts, :only => [:index, :show]
  match "/music" => "music#index", :as => "music"
  resources :photos, :only => [:show, :index]

  resources :posts, :only => [:show]
  resources :videos, :only => [:show]
  resources :albums, :only => [:show, :index] do
    post :buy, :on => :member
    resources :songs, :only => [:show] do
      get :next_song, :on => :collection
      get :intro, :on => :collection
      post :played, :on => :member
      post :buy, :on => :member
    end
  end
  resources :photo_albums do
    resources :photos, :only => [:index]
  end

  resources :channels, :only => [:show, :index] do
    get :next_song, :on => :collection
  end

  # Ads
  get "/ads/next" => "ads#next"

  resources :songs, :only => [:index, :show] do
  end

  #users
  devise_for :users #, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  put '/create_password' => 'users#create_password', :as => 'create_password'
  get '/subscribe' => 'users#subscribe', :as => "subscribe_user"
  put '/subscribe' => "users#subscribe", :as => "create_subscribe_user"
  post '/user/cancel' => "users#cancel", :as => "cancel_membership"
  get '/downloads' => "users#downloads", :as => "downloads_user"
  post '/user/preview' => "users#preview", :as => "preview_user"

  devise_scope :user do
    get "/login" => "sessions#new"
    delete '/logout' => 'sessions#destroy'
    get '/logout' => 'sessions#destroy'
    get '/signup' => 'registrations#new'
    get '/join' => 'registrations#new', :as => 'join'
    #match 'logout', to: 'sessions#destroy', as: 'logout'

    #facebook
    match 'auth/:provider/callback', to: 'sessions#create'
    match 'auth/failure', to: redirect('/')
  end

  #admin
  namespace :admin do
    resources :features, :only => :update
    resources :photos, :only => :index
    resources :videos, :only => :index
    resources :albums, :only => :index
    resources :posts, :only => :index
    resources :users
    #match "channels/:channel_id/albums/:album_id/songs/create_song_upload" => "songs#create_song_upload", :via => [:post], :as => 'create_song_upload'

    #admin/channels
    resources :channels do
      resources :features, :only => :edit
      resources :photo_albums do
        resources :photos
      end
      resources :videos
      resources :posts
      resources :albums do
        resources :songs do
          collection { post :sort }
          member     { post :played }
        end
      end
    end
    match "/pages/channels-help" => "pages#channel_help", :as => "channel_help"
    root :to => "dashboard#index"
  end

  root :to => "channels#show", constraints: lambda {|r| (r.subdomain.present? && r.subdomain != 'www') || !r.host.in?(%w(altimarc.com channels.dev localhost www.channels.dev altimarc-staging.com www.altimarc-staging.com www.altimarc.com altimarc.com))}
  root :to => "home#index"
end

app/models/video.rb
class Video < ActiveRecord::Base

  VIDEO_EXTENSIONS = [
    {:ext => "mp4", :type => "video/mp4"},
    {:ext => "ogg", :type => "video/ogg"},
    {:ext => "webm", :type => "video/webm"}
  ]

  include Rails.application.routes.url_helpers

  belongs_to :channel
  
  # has_one :teaser
  # has_one :performance
  has_one :video_preview
  
  attr_accessible :id, :channel_id, :title, :description, :image, :paid, 
                  :publish_on, :channel, :video, :video_preview_attributes
                  
  image_accessor :image

  validate :image_present_for_publish

  accepts_nested_attributes_for :video_preview
  
  mount_uploader :video, VideoUploader

  scope :published, where('publish_on is not null and publish_on < ?', Time.zone.now)
  scope :recent, published.order('publish_on DESC').limit(4)
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  acts_as_list :scope => :channel 
  
  def filename
    read_attribute :video
  end
  
  def self.current_episode
    published.recent.first
  end
  
  def self.coming_soon(current_video)
    Video.where("publish_on > ?", current_video.publish_on).order('publish_on ASC').limit(4)
  end
  
  def sources
    sources = []
    file_extension = filename.split('.').last
    VIDEO_EXTENSIONS.each do |ext|
      sources << {:src => video.url.gsub(file_extension, ext[:ext]), :type => ext[:type] }
    end
    sources
  end

  def processed!
    update_attribute(:processed, true)
  end

  #one convenient method to pass jq_upload the necessary information
  def to_jq_upload
    {
      "name" => read_attribute(:video),
      "size" => video.size,
      "url" => video.url,
      "delete_url" => admin_channel_video_path(channel.id, id),
      "delete_type" => "DELETE"
    }
  end

  private
    
    def image_present_for_publish
      if !publish_on.blank? && image.nil?
        errors.add(:publish_on, "Image must be present before publishing")
      end
    end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::ApplicationController
  load_and_authorize_resource :channel
  load_and_authorize_resource :video, :through => :channel

  respond_to :html

  def index
  end

  def edit
    @preview = @video.video_preview.nil? ? VideoPreview.new : @video.video_preview    
  end

  def create
    @video.attributes = params[:video]
    @video.title = params[:video][:video].original_filename
    if @video.save
      respond_to do |format|
        format.html {  
          render :json => [@video.to_jq_upload].to_json, 
          :content_type => 'text/html',
          :layout => false
        }
        format.json {  
          render :json => [@video.to_jq_upload].to_json			
        }
      end
    else 
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  def update
    @video.attributes = params[:video]
    unless params[:video][:publish_on].blank?
      @video.publish_on = DateTime.strptime(params[:video][:publish_on], '%m/%d/%Y').to_time
    end 
    if @video.save
      logger.debug("videl valid is #{@video.valid?}")
      flash[:notice] = "Video was successfully updated."
      respond_with @video, :location => admin_channel_videos_url      
    else
      render :action => "edit"
    end
  end

  def destroy
    @video.destroy
    redirect_to admin_channel_videos_url
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  respond_to :html

  def index
    @channels = Channel.all
    @videos = Video.published
  end

  def show
    @video = Video.find(params[:id])
    @channel = current_channel ? current_channel : @video.channel
    @featured_album = @channel.albums.first
    @videos = recent_videos
    if current_user && current_user.facebook?
      Resque.enqueue(MemberWorker, :share_view, {"user_id" => current_user.id, "video_url" => video_url(@video)})
    end
    if @video.present?
      @next_video = Video.coming_soon(@video).first
    end    
  end
  
  private
  
  def recent_videos
    current_videos = @channel.videos.recent
    if current_videos.size < 8
      upcoming_videos = @channel.videos.coming_soon(@video)
      logger.debug("Upcoming videos are #{upcoming_videos.inspect}")
      upcoming_videos.each { |v| current_videos << v }
    end
    logger.debug("current videos are #{current_videos.inspect}")
    current_videos
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/videos_helper.rb
module VideosHelper

  def video_playlist(video)
    if video.class == Video
      sources = current_user && current_user.paid_member? ? video.sources : video.video_preview.sources
    else
      sources = video.sources
    end
    s = []
    sources.each_with_index do |source, index|
      s << "#{index}: {src: '#{source[:src]}', type: '#{source[:type]}'}"
    end
    return s.join(',')
  end
  
  def include_next_episode_preview(current_user, next_video)
    if current_user && current_user.paid_member? && next_video.present? && !next_video.preview.nil?
      s = video_playlist(next_video.video_preview)
      return ",{#{s}, config: {title: \"#{next_video.title}\",className: 'postad',disallowSkip: true}}"
    end
  end
  
end

app/views/videos/index.html.haml
- title @channel.name + "- Videos"

.background-wrapper{ :style => "background: url('#{@channel.background_image.url if @channel.background_image_uid}') repeat-x ##{@channel.background_color};" }
  .content
    .container
      %h3 
        Recent Episodes
        #all_videos.carousel.slide
          / Carousel items
          .carousel-inner
            .item
              %ul.thumbnails
                - @videos.each do |video|
                  %li.span3
                    .thumbnail
                      = image_tag(video.image.thumb('260x180#').url)
                      .caption
                        %h5= video.title.truncate(30)
                        %p.description= video.description.truncate(125)
                        %p
                          = link_with_icon("Watch", channel_video_url(@channel, video), "icon-film icon-white", "btn btn-info pjax")

app/views/videos/show.html.haml
- title @channel.name + " - " + @video.title

- content_for :open_graph do
  %meta{property: "og:title", content: @video.title}
  %meta{property: "og:type", content: "video.other"}
  %meta{property: "og:url",  content: video_url(@video)}
  %meta{property: "og:image",content: @video.image.url(:host => "http://#{request.host}")}
  %meta{property: "og:site_name", content: "Altimarc"}

.content-border
  .row-fluid
    .span
      .videoplayer
        .projekktor_background
          #video
          #player
            %video.projekktor{:controls => "", :poster => "#{@video.image.url}", :title => @video.title}
              - if current_user && current_user.paid_member?
                - @video.sources.each do |source|
                  %source{:src => "#{source[:src]}", :type => source[:type]}
              - else
                - @video.video_preview.sources.each do |source|
                  %source{:src => "#{source[:src]}", :type => source[:type]}
        #video_info
          .row-fluid#video_info_inside
            .span12
              .row-fluid
                .span8
                  %h2
                    = link_to @channel.name, channel_url(@channel)
                    %span - 
                    = @video.title
                  %ul#video_social_sharing
                    -#%li= link_to "Facebook", "#"
                    -#%li= link_to "Tweet", "#"
                    -#TODO: Add share by email function 
                    -#%li= link_to "Share", "#"
                    %li= link_to "Details", "#", :id => "details_link", :class => 'disable-pjax'
                .span4.pull-right
                  #small_ad.pull-right
                    = image_tag('ads/sample-ad.png')
          #details.row-fluid
            .span12
              %p= @video.description
      

  .row-fluid
    .span12
      %h2.heading All Webisodes
      #all_videos.carousel.slide
      - @videos.each_slice(4) do |videos|
        .item{class: carousel_class(@videos, videos)}
          %ul.thumbnails
            - videos.each do |video|
              %li.span3
                .thumbnail
                  %img{:alt => "", :src => video.image.thumb('360x280').url}
                    .caption
                      %h5= video.title.truncate(30)                    
                      %p
                        - if video.publish_on < Time.now
                          - if user_signed_in? && current_user.paid_member?
                            = link_with_icon("Watch", video_path(video), "icon-film icon-white", "connected btn btn-success")
                          - else
                            = link_with_icon("Free Trailer", video_path(video), "icon-film icon-white", "connected btn btn-success")
                        - else
                          = link_with_icon("Coming Soon", "#", "icon-film icon-white", "btn btn-inverse")




:javascript
  $(document).ready(function() {
    var player = projekktor('.projekktor', {
      poster: "#{@video.image.url}",
      controls: true,
      autoplay: true,
      enableFullScreen: true,
      playerFlashMP4: 'http://www.altimarc.com/jarisplayer.swf',
      plugin_display: {
        logoImage: "../../../../assets/html5video/logo.png",
        logoPosition: "tr"
      };
    });
  });