config/routes.rb
Channels::Application.routes.draw do

  #static pages
  match "about" => "pages#about"
  #match "jobs" => "pages#jobs"
  #match "our-team" => "pages#our_team", :as => "our_team"
  #match "press" => "pages#press"
  #match "faq" => "pages#faq"
  #match "customer-support" => "pages#customer_support", :as => "customer_support"
  match "safe-harbor" => "pages#safe_harbor", :as => "safe_harbor"
  match "altimarc-for-your-business" => "pages#altimarc_for_your_business", :as => "altimarc_for_your_business"
  match "privacy" => "pages#privacy", :as => "privacy"
  match "refund" => "pages#refund", :as => "refund"
  match "terms" => "pages#terms", :as => "terms"
  match "copyrights" => "pages#copyrights", :as => "copyrights"
  match "randy-owen-altimarc-coming-soon-video" => "home#index"

  resources :press, :only => [:index, :show]

  #old giveaways
  match "giveaways/kentucky-derby-with-randy-owen" => "giveaways#derby", :as => "derby"
  match "kentucky-derby-with-randy-owen" => redirect("/giveaways/kentucky-derby-with-randy-owen")
  match "giveaways/cma-fanfest" => "giveaways#cma", :as => "cma"
  match "cma-fanfest-with-randy-owen" => redirect("/giveaways/cma-fanfest")
  match "giveaways/thank-you" => "giveaways#thankyou", :as => "thankyou"
  match "t-shirt" => redirect("/giveaways/t-shirt")
  match "giveaways/t-shirt" => "giveaways#tshirt", :as => "tshirt"
  match "giveaways/1965-chevrolet-chevelle" => "giveaways#car", :as => "car"

  #giveaways email
  #match "enter-giveaways(/:id)" => "giveaways#enter_giveaway", :as => 'enter_giveaway'
  match "enter-giveaways" => "giveaways#enter_giveaway", :as => 'enter_giveaway'

  #zencoder
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  post "teaser-zencoder-callback" => "zencoder_callback#teaser", :as => "teaser_zencoder_callback"
  post "performance-zencoder-callback" => "zencoder_callback#performance", :as => "performance_zencoder_callback"
  post "preview-zencoder-callback" => "zencoder_callback#preview", :as => "preview_zencoder_callback"

  #channels
  resources :giveaways, :only => [:index]
  resources :posts, :only => [:index, :show]
  match "/music" => "music#index", :as => "music"
  resources :photos, :only => [:show, :index]

  resources :posts, :only => [:show]
  resources :videos, :only => [:show]
  resources :albums, :only => [:show, :index] do
    post :buy, :on => :member
    resources :songs, :only => [:show] do
      get :next_song, :on => :collection
      get :intro, :on => :collection
      post :played, :on => :member
      post :buy, :on => :member
    end
  end
  resources :photo_albums do
    resources :photos, :only => [:index]
  end

  resources :channels, :only => [:show, :index] do
    get :next_song, :on => :collection
  end

  # Ads
  get "/ads/next" => "ads#next"

  resources :songs, :only => [:index, :show] do
  end

  #users
  devise_for :users #, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  put '/create_password' => 'users#create_password', :as => 'create_password'
  get '/subscribe' => 'users#subscribe', :as => "subscribe_user"
  put '/subscribe' => "users#subscribe", :as => "create_subscribe_user"
  post '/user/cancel' => "users#cancel", :as => "cancel_membership"
  get '/downloads' => "users#downloads", :as => "downloads_user"
  post '/user/preview' => "users#preview", :as => "preview_user"

  devise_scope :user do
    get "/login" => "sessions#new"
    delete '/logout' => 'sessions#destroy'
    get '/logout' => 'sessions#destroy'
    get '/signup' => 'registrations#new'
    get '/join' => 'registrations#new', :as => 'join'
    #match 'logout', to: 'sessions#destroy', as: 'logout'

    #facebook
    match 'auth/:provider/callback', to: 'sessions#create'
    match 'auth/failure', to: redirect('/')
  end

  #admin
  namespace :admin do
    resources :features, :only => :update
    resources :photos, :only => :index
    resources :videos, :only => :index
    resources :albums, :only => :index
    resources :posts, :only => :index
    resources :users
    #match "channels/:channel_id/albums/:album_id/songs/create_song_upload" => "songs#create_song_upload", :via => [:post], :as => 'create_song_upload'

    #admin/channels
    resources :channels do
      resources :features, :only => :edit
      resources :photo_albums do
        resources :photos
      end
      resources :videos
      resources :posts
      resources :albums do
        resources :songs do
          collection { post :sort }
          member     { post :played }
        end
      end
    end
    match "/pages/channels-help" => "pages#channel_help", :as => "channel_help"
    root :to => "dashboard#index"
  end

  root :to => "channels#show", constraints: lambda {|r| (r.subdomain.present? && r.subdomain != 'www') || !r.host.in?(%w(altimarc.com channels.dev localhost www.channels.dev altimarc-staging.com www.altimarc-staging.com www.altimarc.com altimarc.com))}
  root :to => "home#index"
end

app/views/shared/_analytics.html.haml
- if Rails.env.production?
  -#ga
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-29365872-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  -#chartbeat
  :javascript
    var _sf_async_config = { uid: 40355, domain: 'altimarc.com' };
    (function() {
      function loadChartbeat() {
        window._sf_endpt = (new Date()).getTime();
        var e = document.createElement('script');
        e.setAttribute('language', 'javascript');
        e.setAttribute('type', 'text/javascript');
        e.setAttribute('src',
          (("https:" == document.location.protocol) ? "https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/" : "http://static.chartbeat.com/") +
          "js/chartbeat.js");
        document.body.appendChild(e);
      };
      var oldonload = window.onload;
      window.onload = (typeof window.onload != 'function') ?
        loadChartbeat : function() { oldonload(); loadChartbeat(); };
    })();

  -#inspectlet
  %script#inspectletjs{:type => "text/javascript"}
    var __insp = __insp || [];
    __insp.push(['wid', 2644096722]);
    (function() {
    var a = window.onload;
    function __ldinsp(){var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://www.inspectlet.com/inspect/2644096722.js'; document.getElementsByTagName("head")[0].appendChild(insp); }
    window.onload = (typeof window.onload != 'function') ? __ldinsp : function() { a(); __ldinsp(); };
    })();

app/views/shared/_breadcrumb.html.haml
:css
  .breadcrumb {
    -#background: black;
  }

.row-fluid
  .span12
    %ul.breadcrumb
      %li= link_to @channel.name, channel_url(@channel)
      - if params[:controller] == "photos"
        %span.divider /
        %li Photo Albums
        %span.divider /
        %li= @photo_album.title
      - if params[:controller] == "posts"
        %span.divider /
        %li= @post.feature
        %span.divider /
        %li= @post.title

app/views/shared/_channel_menu.html.haml
:css
  #channel_menu {
    margin: 1em 0;
  }
  #channel_menu ul li {
    display: inline;
  }
#channel_menu.span12
  %ul
    %li= link_to "Channel Name Here", "#", :class => "btn"
    / %li= link_to channel.name, root_url(subdomain: channel.subdomain)
    %li= link_to "Videos",  videos_path, :class => "btn"
    %li= link_to "Photos",  photos_path, :class => "btn"
    / - if @channel.feature.audio == true
    /   %li= link_to "Albums",  channel_albums_path(@channel), :class => "btn"
    / - if @channel.feature.news == true
    /   %li= link_to "News",  channel_posts_path(@channel), :class => "btn"
    / - if @channel.feature.events == true
    /   %li= link_to "Events",  channel_events_path(@channel), :class => "btn"
    / - if @channel.feature.vault == true
    /   %li= link_to "Vault", channel_vaults_path(@channel), :class => "btn"
    / - if @channel.feature.giving == true
    /   %li= link_to "Giving",  channel_gives_path(@channel), :class => "btn"
    /   %li= link_to "Living",  channel_lifes_path(@channel), :class => "btn"

app/views/shared/_coming_soon_modal.html.haml
#coming_soon_modal.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h3 Coming soon to Altimarc!
  .modal-body
    .row
      .span#form
        %h3 We're working hard to launch this channel!
        %p For updates on the launch of this channel become a member today.
  .modal-footer
    %a#not_right_now_btn{"data-dismiss" => "modal"} Not right now
    %span or
    %a.btn.btn-primary.btn-large.become_a_member{href: "/subscribe"}
      %i.icon-ok.icon-white
      Become a member

app/views/shared/_current_user.html.erb
<script>
<% if current_user.present? %>
  window.currentUser = '<%= current_user%>';
<% else %>
  window.currentUser = 0;
<% end %>
</script>

app/views/shared/_first_time_visitor_modal.html.haml
:css
  #first_time_vistor h2 {
    text-align: center;
  }
  #first_time_vistor .modal-body {
    text-align: center;
  }
  #first_time_vistor .modal-body img.get-started-social {
    padding-bottom: 20px;
    margin: 5px 0 0;
  }
  #first_time_vistor .modal-body p {
    color: #474747;
  }
  #first_time_vistor .modal-footer a#no_facebook_btn {
    color: #b8b8b8;
    padding-right: 10px;
  }
  #first_time_vistor .modal-footer a#no_facebook_btn:hover {
    color: #474747;
  }
  #first_time_vistor .modal-footer span {
    padding-right: 10px;
    color: #b8b8b8;
  }

#first_time_vistor.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h4 Welcome to the new Altimarc! Here's how it works...
  .modal-body
    .row-fluid
      .span6
        = image_tag('get-started-artist.png')
        %h4 Entertainment. Elevated.
        %p Connect and experience custom video, prizes and unique fan experiences.

      .span6
        = image_tag('get-started-social.png', :class => 'get-started-social')
        %h4 Follow, Share, Discover
        %p Friends will love what you're watching, hearing and winning!
        
  .modal-footer
    %a#no_facebook_btn{:href => "#"} I don't have Facebook
    %span or
    - if current_channel
      %a.btn.btn-primary.btn-large#login{:href => "http://www.#{APP_CONFIG['domain']}/auth/facebook?state=#{current_channel.uuid}"}
        %i.icon-facebook
        Sign in with Facebook
    - else
      %a.btn.btn-primary.btn-large#login{:href => "http://www.#{APP_CONFIG['domain']}/auth/facebook", :host => "www.#{APP_CONFIG['domain']}"}
        %i.icon-facebook
        Sign in with Facebook

app/views/shared/_musicplayer.html.haml
.container-fluid
  .row-fluid
    #player
      #player_control_image
      #inside_player.span12
        #cover-art
          = link_to image_tag("http://placehold.it/70x70"), "javascript:;", :title => "title here"
        #track-meta-data.span10
          %ul{:style => 'margin: 0;'}
            %li= link_to "Track name here", "#link-to-album", :title => "title here", :class => "trackName"
            %li.divider /
            %li= link_to "Artist name here", "#link-to-artist", :title => "artist name here", :class => "artist"
          #waveform
            %img
        #jplayer.jp-player

app/views/shared/_no_facebook_signup_modal.html.haml
#no_facebook_signup.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h3 Sign up
  .modal-body
    .row
      .span5#form
        = simple_form_for(User.new, :as => "user", :url => registration_path("user"), :html => {:class => 'form-horizontal'}) do |f|
          = f.error_notification

          = f.input :first_name, :class => "input-xlarge"
          = f.input :last_name
          = f.input :email, :required => true
          = f.input :password, :required => true
          = f.input :password_confirmation, :hint => '6 characters or longer.', :required => true

          .form-actions{:style => "background: none;"}
            %a.btn.btn-large{"data-dismiss" => "modal"} Cancel
            or
            = f.submit "Create my account", :class => 'btn btn-success btn-large', :id => 'create-my-account'

app/views/shared/_payments_modal.html.haml
=javascript_include_tag "https://js.stripe.com/v1/", "frontend/registrations"

#payments.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h3 Become a Paid Member!
  .modal-body{:style => 'overflow-x: hidden;'}
    .thank_you{:style => "display: none;"}
      %h3 Thanks for paying. Your hard earned money goes towards making Altimarc an even better product.
    .row.payment_header
      .span
        %h4 Paid Members gets access to everything.
        %br
    .row.payment_form
      .span
        = simple_form_for(current_user, :url => subscribe_user_path, :html => {:class => 'form-horizontal', :id => 'subscribe_user'}) do |f|
          = f.error_notification
     
          .stripe_error.error_explanation
            %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
            .payment.span
              .control-group.plans
                = f.input :plan, :collection => [["$6.95 - no gifts", "695"],
                                                 ["$11.95 - cd, t-shirt, one month free", "1195"],
                                                 ["$19.95 - t-shirt vinyle, one month free", "1995"],
                                                 ["$24.95 - t-shirt, vinyl, cd, one month free", "2495"]]
            
              .control-group.credit_card
                %label.control-label{:for => "credit_card"} Credit Card
                .controls
                  %input#card_number.input-large{:type => "text"}
                -#.span
                  -#= image_tag('payments/icon-lock.png')
                -#%strong Secure
                -#= image_tag('payments/img-creditcards.png')
     
              .control-group.security_code
                %label.control-label{:for => "security_code"} Security Code on Card (CVV)
                .controls
                  %input#security_code.input-small{:type => "text", :size => '4', :maxlength => '4'}
              .control-group.card_expiration 
                %label.control-label{:for => "card_month"} Card Expiration
                .controls
                  = select_month nil, {add_month_numbers: true, :use_short_month => true}, {name: nil, id: "card_month", :class => 'input-small'}
                  = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", :class => 'input-small'}
     
              = f.hidden_field :stripe_card_token
     
            -#//coupon
            .row
              .span7{:style => 'text-align: center;'}
                %p
                  = link_to "Got a Coupon Code?", "javascript:;", :id => "coupon_link"
                .control-group#coupon_code
                  %label.control-label{:for => "input01"} Coupon Code
                  .controls
                    %input#input01.input-small{:type => "text"}

            .row
              .span
                %p
                  By clicking Create my account you agree to the
                  = link_to "Terms of Service,", terms_url(:subdomain => "www")
                  = link_to "Privacy,", privacy_url(:subdomain => "www")
                  %span and
                  = succeed "." do
                    = link_to "Refund policies", refund_url(:subdomain => "www")


          .form-actions{:style => "background: none;"}
            = f.submit "Create my account", :class => 'btn-primary btn-success btn-large'

app/views/shared/_unpaid_members_music_modal.html.haml
:css
  #unpaid_members_music_modal .modal-footer a#not_right_now_btn {
    color: #b8b8b8;
    padding-right: 10px;
  }
  #unpaid_members_music_modal .modal-footer a#not_right_now_btn:hover {
    color: #474747;
  }
  #unpaid_members_music_modal .modal-footer span {
    padding-right: 10px;
    color: #b8b8b8;
  }


#unpaid_members_music_modal.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h3 Enjoy Altimarc!
  .modal-body
    .row
      .span#form
        %h3 As a member you will have access to: 
        %ul
          %li Full Music Streaming
          %li Full Video Streaming
          %li Members only Live Streaming Concerts
          %li Prizes including chances to meet your favorite altimarc artists up close and personal
          %li Once in lifetime opportunites
        %strong Receive personalized emails informing you of live events, new videos, new music, latest news and giveaways.
        %br
        %br
        %em ***Also, these pop up messages will go away, and you will have access to full music listening, and full video watching.

  .modal-footer
    %a#not_right_now_btn{"data-dismiss" => "modal"} Not right now
    %span or
    %a.btn.btn-primary.btn-large.become_a_member{href: "/subscribe"}
      %i.icon-ok.icon-white
      Become a member

app/views/shared/_unpaid_members_photos_modal.html.haml
:css
  #unpaid_members_photos_modal .modal-footer a#not_right_now_btn {
    color: #b8b8b8;
    padding-right: 10px;
  }
  #unpaid_members_photos_modal .modal-footer a#not_right_now_btn:hover {
    color: #474747;
  }
  #unpaid_members_photos_modal .modal-footer span {
    padding-right: 10px;
    color: #b8b8b8;
  }

#unpaid_members_photos_modal.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h3 We would love to show you these photos!
  .modal-body
    .row
      .span#form
        %p Become a member today and your hard earn money will go towards making altimarc better and us making you happy!
        %p As a member you will have access to live streaming concerts, prizes, and once in life time oppurtunities.
        %em ***Also, these pop up messages will go away, and you will have exclusive access to photos and more!

  .modal-footer
    %a#not_right_now_btn{"data-dismiss" => "modal"} Not right now
    %span or
    %a.btn.btn-primary.btn-large.become_a_member{href: "/subscribe"}
      %i.icon-ok.icon-white
      Become a member

app/views/shared/_unpaid_members_videos_modal.html.haml
:css
  #unpaid_members_videos_modal .modal-footer a#not_right_now_btn {
    color: #b8b8b8;
    padding-right: 10px;
  }
  #unpaid_members_videos_modal .modal-footer a#not_right_now_btn:hover {
    color: #474747;
  }
  #unpaid_members_videos_modal .modal-footer span {
    padding-right: 10px;
    color: #b8b8b8;
  }


#unpaid_members_videos_modal.modal.hide
  .modal-header
    %a.close{"data-dismiss" => "modal"} ×
    %h3 Thanks for watching! Did you like it?
  .modal-body
    .row
      .span#form
        %h3 We hope so! This was a preview... As a member you will have access to full video watching.
        %em ***Also, these pop up messages will go away, and you will have access to full music listening, and full video watching.

  .modal-footer
    %a#not_right_now_btn{"data-dismiss" => "modal"} Not right now
    %span or
    %a.btn.btn-primary.btn-large.become_a_member{href: "/subscribe"}
      %i.icon-ok.icon-white
      Become a member

app/views/shared/_videoplayer.html.haml
.videoplayer
  .projekktor_background
    #video
    #player
      .projekktor
  #video_info.container
    .row#video_info_inside
      .span8
        %h2
          = link_to @channel.name, channel_url(@channel)
          %span - 
          = @video.title
        %ul#video_social_sharing
          -#%li= link_to "Facebook", "#"
          -#%li= link_to "Tweet", "#"
          -#TODO: Add share by email function 
          -#%li= link_to "Share", "#"
          %li= link_to "Details", "#", :id => "details_link"
      .span4.pull-right
        #small_ad.pull-right
          = image_tag('ads/sample-ad.png')
    #details.row
      .span
        %p= @video.description