config/routes.rb
Channels::Application.routes.draw do

  #static pages
  match "about" => "pages#about"
  #match "jobs" => "pages#jobs"
  #match "our-team" => "pages#our_team", :as => "our_team"
  #match "press" => "pages#press"
  #match "faq" => "pages#faq"
  #match "customer-support" => "pages#customer_support", :as => "customer_support"
  match "safe-harbor" => "pages#safe_harbor", :as => "safe_harbor"
  match "altimarc-for-your-business" => "pages#altimarc_for_your_business", :as => "altimarc_for_your_business"
  match "privacy" => "pages#privacy", :as => "privacy"
  match "refund" => "pages#refund", :as => "refund"
  match "terms" => "pages#terms", :as => "terms"
  match "copyrights" => "pages#copyrights", :as => "copyrights"
  match "randy-owen-altimarc-coming-soon-video" => "home#index"

  resources :press, :only => [:index, :show]

  #old giveaways
  match "giveaways/kentucky-derby-with-randy-owen" => "giveaways#derby", :as => "derby"
  match "kentucky-derby-with-randy-owen" => redirect("/giveaways/kentucky-derby-with-randy-owen")
  match "giveaways/cma-fanfest" => "giveaways#cma", :as => "cma"
  match "cma-fanfest-with-randy-owen" => redirect("/giveaways/cma-fanfest")
  match "giveaways/thank-you" => "giveaways#thankyou", :as => "thankyou"
  match "t-shirt" => redirect("/giveaways/t-shirt")
  match "giveaways/t-shirt" => "giveaways#tshirt", :as => "tshirt"
  match "giveaways/1965-chevrolet-chevelle" => "giveaways#car", :as => "car"

  #giveaways email
  #match "enter-giveaways(/:id)" => "giveaways#enter_giveaway", :as => 'enter_giveaway'
  match "enter-giveaways" => "giveaways#enter_giveaway", :as => 'enter_giveaway'

  #zencoder
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  post "teaser-zencoder-callback" => "zencoder_callback#teaser", :as => "teaser_zencoder_callback"
  post "performance-zencoder-callback" => "zencoder_callback#performance", :as => "performance_zencoder_callback"
  post "preview-zencoder-callback" => "zencoder_callback#preview", :as => "preview_zencoder_callback"

  #channels
  resources :giveaways, :only => [:index]
  resources :posts, :only => [:index, :show]
  match "/music" => "music#index", :as => "music"
  resources :photos, :only => [:show, :index]

  resources :posts, :only => [:show]
  resources :videos, :only => [:show]
  resources :albums, :only => [:show, :index] do
    post :buy, :on => :member
    resources :songs, :only => [:show] do
      get :next_song, :on => :collection
      get :intro, :on => :collection
      post :played, :on => :member
      post :buy, :on => :member
    end
  end
  resources :photo_albums do
    resources :photos, :only => [:index]
  end

  resources :channels, :only => [:show, :index] do
    get :next_song, :on => :collection
  end

  # Ads
  get "/ads/next" => "ads#next"

  resources :songs, :only => [:index, :show] do
  end

  #users
  devise_for :users #, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  put '/create_password' => 'users#create_password', :as => 'create_password'
  get '/subscribe' => 'users#subscribe', :as => "subscribe_user"
  put '/subscribe' => "users#subscribe", :as => "create_subscribe_user"
  post '/user/cancel' => "users#cancel", :as => "cancel_membership"
  get '/downloads' => "users#downloads", :as => "downloads_user"
  post '/user/preview' => "users#preview", :as => "preview_user"

  devise_scope :user do
    get "/login" => "sessions#new"
    delete '/logout' => 'sessions#destroy'
    get '/logout' => 'sessions#destroy'
    get '/signup' => 'registrations#new'
    get '/join' => 'registrations#new', :as => 'join'
    #match 'logout', to: 'sessions#destroy', as: 'logout'

    #facebook
    match 'auth/:provider/callback', to: 'sessions#create'
    match 'auth/failure', to: redirect('/')
  end

  #admin
  namespace :admin do
    resources :features, :only => :update
    resources :photos, :only => :index
    resources :videos, :only => :index
    resources :albums, :only => :index
    resources :posts, :only => :index
    resources :users
    #match "channels/:channel_id/albums/:album_id/songs/create_song_upload" => "songs#create_song_upload", :via => [:post], :as => 'create_song_upload'

    #admin/channels
    resources :channels do
      resources :features, :only => :edit
      resources :photo_albums do
        resources :photos
      end
      resources :videos
      resources :posts
      resources :albums do
        resources :songs do
          collection { post :sort }
          member     { post :played }
        end
      end
    end
    match "/pages/channels-help" => "pages#channel_help", :as => "channel_help"
    root :to => "dashboard#index"
  end

  root :to => "channels#show", constraints: lambda {|r| (r.subdomain.present? && r.subdomain != 'www') || !r.host.in?(%w(altimarc.com channels.dev localhost www.channels.dev altimarc-staging.com www.altimarc-staging.com www.altimarc.com altimarc.com))}
  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #caches_page :index

  def index
    @featured_channel = Channel.find_by_subdomain('fatherofrocknroll')
    @featured_song = Song.recent.first
    @featured_video = Video.recent.first
    @featured_album = Album.find_by_title('Alive at Brushy Mountain State Penitentiary')
    @aliveatbrushy = Channel.find_by_subdomain('aliveatbrushy')
    @randyowen = Channel.find_by_subdomain('randyowen')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_carousel.html.haml
#carousel.row
  .span12
    #slidedeck_frame.skin-slidedeck
      %dl.slidedeck{:style => "height: 380px"}
        - if user_signed_in?
          %dt Altimarc
          %dd
            .row
              .span4.pull-left.wrap-image
                %img{:alt => "", :src => ""}
              .span6.pull-right.wrap-intro
                %h1 Thanks for Choosing Altimarc

        - else
          %dt Join Altimarc
          %dd
            .row
              .span4.pull-left.wrap-image
                %img{:alt => "", :src => ""}
              .span6.pull-right.wrap-intro
                %h1 Join Altimarc
                %p
                  Your membership will allow you to debut exclusive, never before seen concert footage, exclusive world premiere music documentaries, scheduled live concerts, music downloads...
                %p
                  %a.btn.btn-success.btn-large{:href => signup_url} Join Now »
        %dt Brushy Mountain
        %dd
          .row
            .span4.pull-left.wrap-image
              .overlay
              = image_tag('banners/mark-collie.jpg')
            .span6.pull-right.wrap-intro.white-opacity
              %h1 Brushy Mountain
              %p After 113 years, the state of Tennessee closed Brushy Mountain State Penitentiary in June of 2009. But not before country music icon Mark Collie took a two year journey inside the walls of this legendary place.
              %p
                %a.btn.btn-info.btn-large.pull-right{:href => root_url(:subdomain => "markcollie")} Watch Now »

        %dt Randy Owen
        %dd
          .row
            .span4.pull-left.wrap-image
              .overlay
              = image_tag('banners/randy-owen.jpg')
            .span6.pull-right.wrap-intro.white-opacity
              %h1 Randy Owen
              %p Coming Soon.
              -#%p
                -#%a.btn.btn-info.btn-large.pull-right.pjax{:href => root_url(:subdomain => "randyowen")} Randy Owen Channel »

        %dt Sam Phillips
        %dd
          .row
            .span4.pull-left.wrap-image
              .overlay
              = image_tag('banners/sam-phillips.jpg')
            .span6.pull-right.wrap-intro.white-color
              %h1 Sam Phillips
              %p Coming Soon.
              -#%p
                -#%a.btn.btn-info.btn-large.pull-right{:href => root_url(:subdomain => "samphillips")} Sam Phillips Channel »

app/views/home/_new.html.haml
/ Whats New
.row
  .span12
    %ul.breadcrumb.entry-title
      %li.active What's New
    #whats_new.carousel.slide
      / Carousel items
      .carousel-inner
        - @posts.each_slice(4) do |array|
          .item
            %ul.thumbnails
              - array.each do |post|
                %li.span3
                  .thumbnail
                    = image_tag(post.image.thumb('260x180').url)
                    .caption
                      %h5= post.title
                      %p= post.description.truncate(125)
                      %p
                        = link_with_icon("More", "#", "icon-circle-arrow-right icon-white", "btn btn-info pjax")

      / Carousel nav
      %a.carousel-control.left{"data-slide" => "prev", :href => "#whats_new"} ‹
      %a.carousel-control.right{"data-slide" => "next", :href => "#whats_new"} ›

app/views/home/_quote.html.haml
.row-fluid
  .span12
    %blockquote
      %h3
        Mark Collie
        %small 
          It almost killed me, trying to keep this alive. I woke up thinking about this every day for the past 10 years.

app/views/home/_tickets.html.haml
#ticket.row-fluid
  %ul.thumbnails
    - @channels.each do |channel|
      - if channel.active?
        %li.span3
          %a{:href => root_url(:subdomain => channel.subdomain)}
            = image_tag 'ticket-top.png', :class => 'ticket-top'
            .ticket
              .ticket-inside
                .ticket-border
                  .carousel.slide{:id => "ticketSlider-#{channel.id}"}
                    .carousel-inner
                      - channel.photos.limit(5).each do |photo, index|
                        .item
                          = image_tag photo.image.thumb('750x500#n').url, :title => photo.title
                    %h3= channel.name

            = image_tag 'ticket-bottom.png', :class => 'ticket-bottom'
      - else
        %li.span3
          %a.coming_soon{:href => "#coming-soon"}
            = image_tag 'ticket-top.png', :class => 'ticket-top'
            .ticket
              .ticket-inside
                .ticket-border
                  .carousel.slide{:id => "ticketSlider-#{channel.id}"}
                    .carousel-inner
                      .item
                        = image_tag channel.banner_image.thumb('750x500#n').url
                    %h3= channel.name

            = image_tag 'ticket-bottom.png', :class => 'ticket-bottom'

:javascript
  $(document).ready(function() {
    $('.carousel').carousel({
      interval: 5000
    });
  });

app/views/home/index.html.haml
- @keywords = "music, music channels, music tv, watch live, live video production, stream music online, music broadcast, country music, music downloads, music videos, online music, giveaways, music givaways, celebrities giveaways, alive at brushy, aliveatbrushy, mark collie, sam phillips, father of rocknroll"
- @description = "Webisodes, Music, Videos, and Live Entertainment from your favorite celebrities!"

.content-wrapper
  - unless current_user.present? && current_user.paid_member?
    #intro.row-fluid
      .span12{:style => 'text-align: center; margin: 0 0 40px;'}
        %h1 Digital Entertainment Network
        %h2.animated.bounceIn Starting at $6.95/month
        - if current_user.present?
          = link_to "Subscribe Now", subscribe_user_url(:subdomain => 'www'), :class => 'btn btn-large btn-success'
        - else
          = link_to "Join Now", join_url(:subdomain => 'www'), :class => 'btn btn-large btn-success'

  = render 'home/tickets'

  %hr

  .row-fluid
    .span{:style => 'text-align: center;'}
      %h3 Featured Channel
  .row-fluid
    .span
      %a{:href => root_url(:subdomain => @featured_channel.subdomain)}
        = image_tag(@featured_channel.banner_image.url, :class => 'img-rounded img-polaroid')
  %hr

  .row-fluid.featured
    .span4
      %a{:href => album_song_url(@featured_album, @featured_song)}
        = image_tag(@featured_song.album.image.thumb('753x592#').url, :class => 'img-rounded img-polaroid')
        %h4 Featured Song
        %p= @featured_song.title

    .span4
      %a{:href => video_url(@featured_video, :subdomain => @featured_video.channel.subdomain)}
        = image_tag(@featured_video.image.thumb('753x592#').url, :class => 'img-rounded img-polaroid')
        %h4 Featured Video
        %p= @featured_video.title
    .span4
      %a.featured-popover{:href => album_url(@featured_album, :subdomain => @featured_album.channel.subdomain)}
        = image_tag(@featured_album.image.thumb('753x592#').url, :class => 'img-rounded img-polaroid')
        %h4 Featured Album
        %p= @featured_album.title
  -#%hr
  -#.row-fluid
    -#.span{:style => 'text-align: center;'}
      -#%h3 Featured Giveaway