config/routes.rb
Channels::Application.routes.draw do

  #static pages
  match "about" => "pages#about"
  #match "jobs" => "pages#jobs"
  #match "our-team" => "pages#our_team", :as => "our_team"
  #match "press" => "pages#press"
  #match "faq" => "pages#faq"
  #match "customer-support" => "pages#customer_support", :as => "customer_support"
  match "safe-harbor" => "pages#safe_harbor", :as => "safe_harbor"
  match "altimarc-for-your-business" => "pages#altimarc_for_your_business", :as => "altimarc_for_your_business"
  match "privacy" => "pages#privacy", :as => "privacy"
  match "refund" => "pages#refund", :as => "refund"
  match "terms" => "pages#terms", :as => "terms"
  match "copyrights" => "pages#copyrights", :as => "copyrights"
  match "randy-owen-altimarc-coming-soon-video" => "home#index"

  resources :press, :only => [:index, :show]

  #old giveaways
  match "giveaways/kentucky-derby-with-randy-owen" => "giveaways#derby", :as => "derby"
  match "kentucky-derby-with-randy-owen" => redirect("/giveaways/kentucky-derby-with-randy-owen")
  match "giveaways/cma-fanfest" => "giveaways#cma", :as => "cma"
  match "cma-fanfest-with-randy-owen" => redirect("/giveaways/cma-fanfest")
  match "giveaways/thank-you" => "giveaways#thankyou", :as => "thankyou"
  match "t-shirt" => redirect("/giveaways/t-shirt")
  match "giveaways/t-shirt" => "giveaways#tshirt", :as => "tshirt"
  match "giveaways/1965-chevrolet-chevelle" => "giveaways#car", :as => "car"

  #giveaways email
  #match "enter-giveaways(/:id)" => "giveaways#enter_giveaway", :as => 'enter_giveaway'
  match "enter-giveaways" => "giveaways#enter_giveaway", :as => 'enter_giveaway'

  #zencoder
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  post "teaser-zencoder-callback" => "zencoder_callback#teaser", :as => "teaser_zencoder_callback"
  post "performance-zencoder-callback" => "zencoder_callback#performance", :as => "performance_zencoder_callback"
  post "preview-zencoder-callback" => "zencoder_callback#preview", :as => "preview_zencoder_callback"

  #channels
  resources :giveaways, :only => [:index]
  resources :posts, :only => [:index, :show]
  match "/music" => "music#index", :as => "music"
  resources :photos, :only => [:show, :index]

  resources :posts, :only => [:show]
  resources :videos, :only => [:show]
  resources :albums, :only => [:show, :index] do
    post :buy, :on => :member
    resources :songs, :only => [:show] do
      get :next_song, :on => :collection
      get :intro, :on => :collection
      post :played, :on => :member
      post :buy, :on => :member
    end
  end
  resources :photo_albums do
    resources :photos, :only => [:index]
  end

  resources :channels, :only => [:show, :index] do
    get :next_song, :on => :collection
  end

  # Ads
  get "/ads/next" => "ads#next"

  resources :songs, :only => [:index, :show] do
  end

  #users
  devise_for :users #, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  put '/create_password' => 'users#create_password', :as => 'create_password'
  get '/subscribe' => 'users#subscribe', :as => "subscribe_user"
  put '/subscribe' => "users#subscribe", :as => "create_subscribe_user"
  post '/user/cancel' => "users#cancel", :as => "cancel_membership"
  get '/downloads' => "users#downloads", :as => "downloads_user"
  post '/user/preview' => "users#preview", :as => "preview_user"

  devise_scope :user do
    get "/login" => "sessions#new"
    delete '/logout' => 'sessions#destroy'
    get '/logout' => 'sessions#destroy'
    get '/signup' => 'registrations#new'
    get '/join' => 'registrations#new', :as => 'join'
    #match 'logout', to: 'sessions#destroy', as: 'logout'

    #facebook
    match 'auth/:provider/callback', to: 'sessions#create'
    match 'auth/failure', to: redirect('/')
  end

  #admin
  namespace :admin do
    resources :features, :only => :update
    resources :photos, :only => :index
    resources :videos, :only => :index
    resources :albums, :only => :index
    resources :posts, :only => :index
    resources :users
    #match "channels/:channel_id/albums/:album_id/songs/create_song_upload" => "songs#create_song_upload", :via => [:post], :as => 'create_song_upload'

    #admin/channels
    resources :channels do
      resources :features, :only => :edit
      resources :photo_albums do
        resources :photos
      end
      resources :videos
      resources :posts
      resources :albums do
        resources :songs do
          collection { post :sort }
          member     { post :played }
        end
      end
    end
    match "/pages/channels-help" => "pages#channel_help", :as => "channel_help"
    root :to => "dashboard#index"
  end

  root :to => "channels#show", constraints: lambda {|r| (r.subdomain.present? && r.subdomain != 'www') || !r.host.in?(%w(altimarc.com channels.dev localhost www.channels.dev altimarc-staging.com www.altimarc-staging.com www.altimarc.com altimarc.com))}
  root :to => "home#index"
end

app/models/giveaway.rb
class Giveaway < ActiveRecord::Base

  validates :email, :presence => true, 
                      :length => {:minimum => 3, :maximum => 254, :message => "Email is to short"},
                      :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Email is invalid"}
end

app/controllers/giveaways_controller.rb
class GiveawaysController < ApplicationController
  def index
  end

  def derby
  end

  def cma
  end

  def tshirt
  end

  def car
  end

  def thankyou
  end

  def enter_giveaway
    @giveaway = Giveaway.new(params[:giveaway])
    if @giveaway.save
      GiveawayMailer.registration_confirmation(@giveaway).deliver
      flash[:success] = "You're registered!"
    else
      flash[:error] = "Please check your email or confirm that you haven't entered already."
    end
    redirect_to root_url
  end

end

app/helpers/giveaways_helper.rb
module GiveawaysHelper
end

app/views/giveaways/car.html.haml
- title "CMA FanFest Nashville"

.content-border
  .row-fluid
    .span
      = image_tag("car-banner.jpg")
  .row-fluid
    .span
      .inside.giveaway
        %h1 1965 CHEVROLET CHEVELLE FROM ALTIMARC.COM!
        - if @giveaway.errors.any?
          - @giveaway.errors.messages.each do |message|
            .message= message.last.last.html_safe
        .row-fluid
          .span4{:style => 'margin: 0 auto; float: none;'}
            = simple_form_for @giveaway, :url => enter_giveaway_path, :html => {:class => 'wellclear form-inline'} do |f|
              = f.input :car, :as => :hidden, :input_html => {:value => 1}
              .span{:style => 'width: 270px;padding-top: 2px;'}
                = f.input :email, :input_html => {:class => "input-xlarge", :placeholder => "Email"}, :label => false
              .span{:style => 'width: 133px; margin-left: 20px;'}
                %button.btn.btn-danger{:type => "submit"} Sign Up To Win!

        %div
          %h3 SOME AUTOMOBILES ARE LEGENDS.  THERE ARE SOME BRANDS THAT CONTINUE TO FASCINATE EVEN THE MOST HARD CORE COLLECTORS.  FINDING SUCH A CAR IN THIS DAY AND AGE IS PROVING MORE DIFFICULT.  AND THEN, WHEN YOU FIND IT, IT MAY TAKE THOUSANDS OF DOLLARS TO GET IT CLOSE TO ITS ORIGINAL CONDITION.
          %p SOME SAY SUCH A CAR DOESN’T EXIST UNLESS YOU HAVE THE BUCKS TO SHELL OUT.  SOME SAY IT’S IMPOSSIBLE TO OWN.  ALTIMARC.COM HAS SUCH A CAR AND WE’RE ON A MISSION TO FIND THE PERFECT OWNER.
          %p THE CAR IS A ONE OF KIND, COMPLETELY RESTORED 1965 CHEVROLET CHEVELLE.  IT’S BRANDY WINE WITH TAN INTERIOR.  IT HAS ONLY 2000 MILES.  THAT’S RIGHT, 2000 MILES!  A SIMPLY STUNNING, DROP DEAD GORGEOUS KANDY BRANDYWINE SS WITH A STRAIGHT AS AN ARROW BODY.  PLENTY OF POWER UNDER THE HOOD.  A STATE OF THE ART SOUND SYSTEM.  OVER $10,000 INVESTED UNDER THE HOOD ALONE!
          %p NOW, IT NEEDS AN OWNER.  ARE YOU THAT PERSON?  CAN YOU HANDLE SUCH AN INVESTMENT?  IF SO, CHECK BACK SOON BECAUSE THIS IS A ONCE IN A LIFETIME OPPORTUNITY FROM ALTIMARC.COM
          %p DETAILS ARE COMING SOON ON HOW YOU CAN WIN .   IN 2013, YOU COULD BE THE OWNER OF THIS 1965 CHEVROLET CHEVELLE FROM ALTIMARC.COM!

app/views/giveaways/cma.html.haml
- title "CMA FanFest Nashville"
.content-border
  = image_tag("cma-music-fest-banner.png")

  .inside.giveaway{:style => 'padding-top: 20px;'}
    %h1 CMA Music Festival Nashville

    %p
      FRIDAY, JUNE 8TH THRU SUNDAY, JUNE 10TH (3 DAYS AND 2 NIGHTS)

    %h2{:style => "color:red; padding: 20px 0;"} Congratulations to Cindy, from Shenandoah Valley, Virginia!!<br/> Thank y'all for signing up!!

    %div{ :style => "text-align: center;" }
      %h2
        PROUDLY PRODUCED BY “DREAM TRIP OF A LIFETIME”
      %strong
        EVENING SUPERSTAR CONCERT SERIES AT LP FIELD
      %strong
        DAYTIME CONCERT SERIES AT RIVERFRONT PARK 

      %ul
        %li ARTIST EXHIBIT BOOTHS AT NASHVILLE CONVENTION CENTER
        %li FAMILY ZONE, FUN ZONE & SPORTS ZONE 
        %li COUNTRY MUSIC HALL OF FAME & MUSEUM 
        %li WILD HORSE SALOON DANCE PARTY 
        %li WORLD FAMOUS MUSIC ROW  
        %li HONKY TONKIN’ ON LOWER BROADWAY
        %li ROUNDTRIP COACH CLASS AIRLINE TRANSPORTATION
        %li DELUXE LODGING AT HOTEL PRESTON
        %li DELUXE GROUND TRANSPORTATION 
        %li VIP RESERVATIONS AT NASHVILLE’S FUN RESTAURANTS 
        %li AIRPORT GREETINGS & ALOHAS 
        %li GROUP MEETING, GREETINGS & INTRODUCTIONS 
        %li WELCOME RECEPTION & BON VOYAGE PARTY 
        %li COMPREHENSIVE ELECTRONIC TRIP WINNER KIT 
        %li TRIP PARTICIPANT LAMINATES & LANYARDS 
        %li TRIP WINNER CONGRATULATIONS TELEPHONE CALL FROM J.D. HAAS 
        %li TRIP WINNER CONGRATULATIONS EMAIL NEWSLETTER 
        %li WORLD CLASS TRIP STAFF 
        %li VIP HOSPITALITY 
        %li HOST & ESCORT AT ALL EVENTS 
        %li GENERAL SUPERVISION
        %li 24 HOUR-A-DAY EMERGENCY ACCESS
        %li 30 YEARS OF WORLD CLASS SERVICE  
        %li TRIP HOST J.D. HAAS

      %em
        * EACH TRIP IS FOR ONE WINNER AND THEIR GUEST. DOES NOT INCLUDE MEALS OR SPENDING CASH. ALL TRIP EVENTS, VENUES AND DATES SUBJECT TO CHANGE. CERTAIN CONDITIONS APPLY TO AIRFARE.

      %hr
        .rules
          %strong Rules:
          %p
            Unless otherwise stated herein, all contests and/or promotions offered
            on 
            = link_to "altimarc.com", root_url
            are open to all US citizens, 21 years of age or older. No purchase
            is necessary; however data and message rates may apply. The current “Contest”
            offered on 
            = link_to "altimarc.com", root_url
            is entitled CMA MUSIC FESTIVAL – “DREAM TRIP OF A LIFETIME”. This contest runs 
            from March 22, 2012 to May 14, 2012. Entries are limited to one per household. Employees of 
            = link_to "altimarc.com", root_url
            and/or their family members are not eligible. Odds of winning depend on the number of entrants.
            Each selected winner is responsible for all applicable federal, state and local taxes
            and/or taxes in the country of residency and each selected winner agrees to abide
            by any additional guidelines provided by the producer of the Contest, J.D. Haas
            Entertainment (“Additional Guidelines”). By entering the Contest, you automatically grant
            = link_to "altimarc.com", root_url
            permission to use your name and likeness for promotional purposes in perpetuity. With respect to the Contest, 
            = link_to "altimarc.com", root_url
            is not responsible for any cancellations, airline delays, venue changes, artists’ cancellations or any other
            changes due to travel delays, illness and/or all acts of God.

          %p
            One winner will be selected from all entries for the 
            = link_to "altimarc.com", root_url
            Contest and will be notified of their selection within 3 business days. No more than the advertised prize
            shall be awarded. The winner must respond (and provide the necessary information
            for their selected guest) within 48 business hours of being notified or an alternate
            winner will be selected. There is no substitution of prizes. The prize(s) as advertised
            will be awarded if properly claimed by the winner according to these rules and the
            Additional Guidelines and if there are sufficient eligible entries. 
            = link_to "altimarc.com", root_url
            does not make, and is not responsible in any manner for, any warranties, representations,
            or guarantees, express or implied, in fact or law, relating to any prizes, regarding
            the use, value or enjoyment of the prize, including, without limitation, its quality,
            mechanical condition, merchantability, or fitness for a particular purpose. The prize
            may not be sold or transferred and is not convertible to cash. As such, the winner (and
            selected guest) hereby indemnify and hold harmless, 
            = link_to "altimarc.com", root_url
            ,
            = link_to "altimarc.com", root_url
            and their owners, employees, representatives, agents, directors, officers, successors and/or
            assigns from any and all claims or liability, including but not limited to such liability
            arising from any acts or omissions resulting in injury to body or property of winner
            (and selected guest) while participating in the Contest. All other additional costs and
            expenses related to prize acceptance and use not specified herein as being provided
            are the sole responsibility of winner(s). If the winner is disqualified or is found to be
            ineligible for the Contest, 
            = link_to "altimarc.com", root_url
            reserves the right to determine an alternate winner or not to award the prize, at its sole discretion.

app/views/giveaways/derby.html.haml
- title 'Kentucky Derby with Randy Owen'
.content-border
  = image_tag("randy-derby.jpg")

  .inside.giveaway{:style => 'padding-top: 20px;'}
    %h1 Kentucky Derby Giveaway
    
    %p FRIDAY, MAY 4TH THROUGH SUNDAY, MAY 6TH (3 DAYS AND 2 NIGHTS)

    %h2{:style => "color:red; padding: 20px 0;"} Congratulations to Markcus, from Las Vegas, Nevada!!<br/> Thank y'all for signing up!!

    %div{ :style => "text-align: center;" }
      %h2
        PROUDLY PRODUCED BY “DREAM TRIP OF A LIFETIME”
      %strong
        "UNBRIDLED EVE GALA" STARRING RANDY OWEN IN CONCERT WITH:

      %ul
        %li CELEBRITY RED CARPET ARRIVALS
        %li COCKTAIL RECEPTION
        %li GOURMET DINNER
        %li DANCING
        %li LIVE & SILENT AUCTIONS
        %li SPECIALTY BARS
        %li MEET & GREET & PICTURES & AUTOGRAPHS WITH RANDY OWEN
        %li 138TH RUNNING OF THE KENTUCKY DERBY
        %li KENTUCKY DERBY MUSEUM
        %li FOURTH STREET LIVE
        %li DERBY CONCERT
        %li LOUISVILLE SLUGGER MUSEUM & FACTORY
        %li FOURTH STREET LIVE ENTERTAINMENT & SHOPPING DISTRICT
        %li RIVERFRONT PARK
        %li DELUXE LODGING AT TBA
        %li ROUNDTRIP COACH CLASS AIRLINE TRANSPORTATION
        %li DELUXE GROUND TRANSPORTATION
        %li AIRPORT GREETINGS & ALOHAS
        %li COMPREHENSIVE ELECTRONIC TRIP WINNER KIT
        %li TRIP PARTICIPANT LAMINATES AND LANYARDS
        %li TRIP WINNER CONGRATULATIONS TELEPHONE CALL FROM J.D. HAAS
      %li TRIP WINNER CONGRATULATIONS EMAIL NEWSLETTER
      %li WORLD CLASS TRIP STAFF
      %li VIP HOSPITALITY
      %li HOST & ESCORT AT ALL EVENTS
      %li GENERAL SUPERVISION
      %li 24 HOUR-A-DAY EMERGENCY ACCESS
      %li 30 YEARS OF WORLD CLASS SERVICE

    %em
      * EACH TRIP IS FOR ONE WINNER AND THEIR GUEST. DOES NOT INCLUDE MEALS OR SPENDING CASH. ALL TRIP EVENTS, ARTISTS, VENUES AND DATES SUBJECT TO CHANGE. CERTAIN CONDITIONS APPLY TO AIRFARE.

    %hr
      .rules
        %strong Rules:
        %p
          Unless otherwise stated herein, all contests and/or promotions offered
          on 
          = link_to "altimarc.com", root_url 
          are open to all US citizens, 21 years of age or older. No purchase
          is necessary; however data and message rates may apply. The current “Contest”
          offered on 
          = link_to "altimarc.com", root_url
          is entitled “KENTUCKY DERBY”.
          This contest runs from March 22, 2012 to April 24, 2012. Entries are limited to
          one per household. Employees of
          = link_to "altimarc.com", root_url 
          and/or their family members are
          not eligible. Odds of winning depend on the number of entrants. Each selected
          winner is responsible for all applicable federal, state and local taxes and/or
          taxes in the country of residency and each selected winner agrees to abide by
          any additional guidelines provided by the producer of the Contest, J.D. Haas
          Entertainment (“Additional Guidelines”). By entering the Contest, you automatically
          grant 
          = link_to "altimarc.com", root_url 
          permission to use your name and likeness for promotional purposes in perpetuity. With respect to the Contest, 
          = link_to "altimarc.com", root_url 
          is not responsible for any cancellations, airline delays, venue changes, artists’ cancellations or any other
          changes due to travel delays, illness and/or all acts of God.
          
        %p
          One winner will be selected from all entries for the
          = link_to "altimarc.com", root_url 
          Contest and will be notified of their selection within 3 business days. No more than the advertised prize
          shall be awarded. The winner must respond (and provide the necessary information
          for their selected guest) within 48 business hours of being notified or an alternate
          winner will be selected. There is no substitution of prizes. The prize(s) as advertised
          will be awarded if properly claimed by the winner according to these rules and the
          Additional Guidelines and if there are sufficient eligible entries.
          = link_to "altimarc.com", root_url 
          does not make, and is not responsible in any manner for, any warranties, representations,
          or guarantees, express or implied, in fact or law, relating to any prizes, regarding
          the use, value or enjoyment of the prize, including, without limitation, its quality,
          mechanical condition, merchantability, or fitness for a particular purpose. The prize
          may not be sold or transferred and is not convertible to cash. As such, the winner (and
          selected guest) hereby indemnify and hold harmless,
          = link_to "altimarc.com", root_url
          , 
          = link_to "altimarc.com", root_url 
          and their owners, employees, representatives, agents, directors, officers, successors and/or
          assigns from any and all claims or liability, including but not limited to such liability
          arising from any acts or omissions resulting in injury to body or property of winner
          (and selected guest) while participating in the Contest. All other additional costs and
          expenses related to prize acceptance and use not specified herein as being provided
          are the sole responsibility of winner(s). If the winner is disqualified or is found to be
          ineligible for the Contest, 
          = link_to "altimarc.com", root_url 
          reserves the right to determine an alternate winner or not to award the prize, at its sole discretion.

app/views/giveaways/index.html.haml
- title "Giveaways"
.content-wrapper
  .row-fluid
    .span12
      %h1.page-heading Current Giveaways
      %ul.thumbnails
        %li.span4
          .thumbnail
            = link_to image_tag('car-banner-icon.jpg'), car_url(:subdomain => 'www')
            .caption
              %h5 1965 CHEVROLET CHEVELLE
        %li.span4
          .thumbnail
            = link_to image_tag('tshirt-banner-icon.jpg'), tshirt_url(:subdomain => 'www')
            .caption
              %h5 Free Altimarc T-shirt

  .row-fluid
    .span12
      %h2.page-heading Past Giveaways
      %ul.thumbnails
        %li.span4
          .thumbnail
            = link_to image_tag('cma-banner-icon.png'), cma_url(:subdomain => 'www')
            .caption
              %h5 CMA Music Festival Nashville
        %li.span4
          .thumbnail
            = link_to image_tag('derby-banner-icon.png'), derby_url(:subdomain => 'www')
            .caption
              %h5 Kentucky Derby Giveaway

app/views/giveaways/thankyou.html.haml
.content-border
  = image_tag("altimarc-banner.png")
  .inside
    %h2{:style => "margin: 50px 0 150px 0;"}
      Check your email account for important information regarding your registeration for this contest, plus other exciting opportunities coming soon to
      = link_to "Altimarc.com", root_path

app/views/giveaways/tshirt.html.haml
- title "Free Altimarc T-shirt"

.content-border
  = image_tag("tshirt-banner.jpg")

  .inside.giveaway
    %h1 WEEKLY WINNERS
  .row-fluid
    .span{:style => 'margin: 0 auto; float: none; width: 340px;'}
      .div{:style => 'padding: 20px;'}
        .fb-like{"data-font" => "arial", "data-href" => "http://facebook.com/altimarc", "data-send" => "false", "data-show-faces" => "false", "data-width" => "300"}

:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=505364239479743";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));